services:
  shareddbtest:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shared_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - shareddbtest_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=shareddbtest
      - MYSQL_DATABASE=shared_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - APP_URL=http://10.10.10.3:8200
      - MYSQL_PORT_3306_TCP_ADDR=shareddbtest
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=shared_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./snipe_data:/config
    ports:
      - "8200:80"
    depends_on:
      - shareddbtest
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    restart: always
    ports:
      - 3004:3000
      - 222:22
    volumes:
      - gitea:/data
    environment:
      - DB_TYPE=mysql
      - DB_HOST=shareddbtest
      - DB_NAME=shared_db
      - DB_USER=user
      - DB_PASSWD=password

volumes:
  shareddbtest_data:
  nextcloud:
  gitea: