
services:
  shareddatabase:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shared_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=shareddatabase
      - MYSQL_DATABASE=shared_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  snipeit:
    image: snipe/snipe-it
    restart: always
    ports:
      - 8081:80
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=shareddatabase
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=shared_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  gitea:
    image: gitea/gitea:latest
    restart: always
    ports:
      - 3004:3000
      - 222:22
    volumes:
      - gitea:/data
    environment:
      - DB_TYPE=mysql
      - DB_HOST=shareddatabase:3306
      - DB_NAME=shared_db
      - DB_USER=user
      - DB_PASSWD=password

  bookstack:
    image: linuxserver/bookstack
    restart: always
    ports:
      - 6875:80
    environment:
      - DB_HOST=shareddatabase:3306
      - DB_DATABASE=shared_db
      - DB_USERNAME=user
      - DB_PASSWORD=password

volumes:
  db_data:
  nextcloud:
  gitea: