global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.3:9323']
  - job_name: 'nextjs'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.3:3000']
  - job_name: 'nestjs'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.3:3001']