global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['shareddbtest:3306']

  - job_name: 'nextcloud'
    static_configs:
      - targets: ['nextcloud:80']

  - job_name: 'snipe-it'
    static_configs:
      - targets: ['snipe-it:80']

  - job_name: 'gitea'
    static_configs:
      - targets: ['gitea:3000']